pipeline:
  identifier: Build_go_pipeline_sample_1699258651304
  name: Build go-pipeline-sample
  orgIdentifier: default
  projectIdentifier: project3
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1699258630140
        repoName: go-pipeline-sample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    command: go build
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotest
                  name: go_test
                  spec:
                    command: go test -v ./...
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
